accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from receipts.views import (
    ReceiptsListView,
    ReceiptsCreateView,
    AccountsCreateView,
    CategoriesCreateView,
    ExpenseCategoryListView,
    AccountListView,
)

urlpatterns = [
    path("", ReceiptsListView.as_view(), name="home"),
    path("account/", AccountListView.as_view(), name="account"),
    path("categories/", ExpenseCategoryListView.as_view(), name="categories"),
    path("create/", ReceiptsCreateView.as_view(), name="receipts_create"),
    path(
        "accounts/create/",
        AccountsCreateView.as_view(),
        name="accounts_create",
    ),
    path(
        "categories/create/",
        CategoriesCreateView.as_view(),
        name="categories_create",
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

usermodel = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        usermodel, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        usermodel, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField(auto_now_add=True)
    purchaser = models.ForeignKey(
        usermodel, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account, related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()

    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    CreateView,
    TemplateView,
)
from receipts.models import Receipt, Account, ExpenseCategory


# LIST


class ReceiptsListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "category/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


# CREATE


class ReceiptsCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class AccountsCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account")


class CategoriesCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "category/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("categories")

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
        {% if user.is_authenticated %}
    <li>
        <a href="{% url "logout" %}">--Logout--</a>
        {% else %}
        <a href="{% url "signup" %}">--Sign Up--</a>
        <a href="{% url "login" %}">--Login--</a>
    </li>
        {% endif %}
</head>
<body>
    <header>
        <a href="{% url "home" %}">--Home--</a>
        <a href="{% url "account" %}">--Accounts--</a>
        <a href="{% url "categories" %}">--Expense Categories--</a>
        <a href="{% url "receipts_create" %}">--Create Receipts--</a>
        <a href="{% url "categories_create" %}">--Create Expense Category--</a>
        <a href="{% url "accounts_create" %}">--Create Account--</a>
    </header>
    {% block content %}
    {% endblock content%}
</body>
</html>

receipts/templates/accounts/create.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Create</button>
</form>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}
{% block content %}
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number</th>
            <th>Number of receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for accounts in account_list %}
        <tr>
            <td>{{accounts.name}}</td>
            <td>{{accounts.number}}</td>
            <td>{{accounts.receipt.name | length}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipts/templates/category/create.html
{% extends "base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create</button>
    </form>
{% endblock content %}

receipts/templates/category/list.html
{% extends 'base.html' %}
{% block content %}
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number of receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for category in expensecategory_list %}
        <tr>
            <td>{{category.name}}</td>
            <td>{{category.receipts.all | length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Create</button>
</form>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% block content %}
<table>
    <thead>
        <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
        </tr>
    </thead>
    <tbody>
        {% for receipts in receipt_list %}
        <tr>
            <td>{{receipts.vendor}}</td>
            <td>{{receipts.total}}</td>
            <td>{{receipts.tax}}</td>
            <td>{{receipts.date}}</td>
            <td>{{receipts.category}}</td>
            <td>{{receipts.account}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}